### ISSUE TITLE
Syntax Highlighting Error When Commenting Heex Template

### ISSUE THREAD

**Issue by Miserlou** [elixir-lsp/vscode-elixir-ls#215]
OSX, latest released Elixir and VSCode.

Before:
<img width="547" alt="Screen Shot 2021-11-15 at 1 56 12 PM" src="https://user-images.githubusercontent.com/139987/141785885-b6db570a-c159-4f2e-baaa-e506ec2d8d98.png">

After selecting the whole block and `Command+/`'ing:
<img width="494" alt="Screen Shot 2021-11-15 at 1 56 31 PM" src="https://user-images.githubusercontent.com/139987/141785945-f240735c-d023-42fa-93c4-e0ee7ce6e7df.png">

I would expect the whole block to become green, it looks like the commenting stops at the `do %>`.

**Comment by axelson** [comment]
Hi @Miserlou vscode-elixir-ls does not support syntax highlighting for `.heex` files. Instead we recommend that you use https://github.com/phoenixframework/vscode-phoenix

Although what you have is not actually a syntax highlighting problem, the syntax highlighting is correct because any `%>` will end a comment block. As far as I know there's no comment syntax in `.eex` or `.heex` that would allow you to comment that whole block in one swoop.
