### ISSUE TITLE
HTML intellisense in ~L/H sigil.

### ISSUE THREAD

**Issue by kingdevnl** [elixir-lsp/vscode-elixir-ls#243]
Is it possible to get html/ex autocompletion inside the ~L sigil?

**Comment by lukaszsamson** [comment]
Elixir intelisense is working. HTML is not.

**Comment by dvic** [comment]
If you add the following

```
"emmet.includeLanguages": {
  "elixir": "html",
  "phoenix-heex": "html"
},
"emmet.triggerExpansionOnTab": true,
```

It will actually work (I tested it in HEEx sigils). It works because of the `emmet.triggerExpansionOnTab` setting, which expands the tag on TAB even if there is no item in the autocomplete list. However, it doesn't work for `div` because this autocompletes to the `div()` function in `Kernel` :( @lukaszsamson is there a way to disable the autocomplete for certain functions, and maybe just in the sigil? 

In any case, this "hack" works for aby html element that is not shadowed by a function in scope.

**Comment by azyzz228** [comment]
> If you add the following
> 
> ```
> "emmet.includeLanguages": {
>   "elixir": "html",
>   "phoenix-heex": "html"
> },
> "emmet.triggerExpansionOnTab": true,
> ```
> 
> It will actually work (I tested it in HEEx sigils). It works because of the `emmet.triggerExpansionOnTab` setting, which expands the tag on TAB even if there is no item in the autocomplete list. However, it doesn't work for `div` because this autocompletes to the `div()` function in `Kernel` :( @lukaszsamson is there a way to disable the autocomplete for certain functions, and maybe just in the sigil?
> 
> In any case, this "hack" works for aby html element that is not shadowed by a function in scope.

It works perfectly well but then when writing elixir code, you get a lot of emmet suggestions which is annoying. Would be great to configure Emmet to work only inside of `~H` as you suggested

**Comment by lukaszsamson** [comment]
I think the proper solution would be to create a dedicated language server for `html-eex`

**Comment by lukaszsamson** [comment]
After more thought I'm sure that a dedicated phoenix language server is a way to go. There's already https://github.com/phoenixframework/vscode-phoenix which handles the H sigil. H sigil was supported but it turned to be a mistake breaking `phoenix-heex` grammar. This extension has supported E/L sigils but given that both are now deprecated for more than a year it safe to assume that in a year almost nobody will need support for them
