### ISSUE TITLE
Breakpoints not working for DEBUG CONSOLE triggered commands

### ISSUE THREAD

**Issue by dimpdash** [elixir-lsp/vscode-elixir-ls#265]
I'm experiencing this issue. when I add a breakpoint and enter a command in the DEBUG CONSOLE I get an error:

"debugged process #PID<0.179.0> exited with reason no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started"

![image](https://user-images.githubusercontent.com/20607550/190157778-bffbe95a-b75c-4033-a560-905bf192a2ee.png)
However when starting the debugging breakpoints work.

The log points in vscode seem to still work though.

I've tried windows and wsl and both have the same issue.

Tested on this sample repo here
https://github.com/BrooklinJazz/debugging_elixir

_Originally posted by @dimpdash in https://github.com/elixir-lsp/vscode-elixir-ls/issues/158#issuecomment-1246716123_

**Comment by dimpdash** [comment]
ElixirLS Version 0.11.0

**Comment by dimpdash** [comment]
Works when lines are handel_call on a Gen Server. Maybe it has something to do with the root application PID

**Comment by lukaszsamson** [comment]
If I understand correctly you try to debug a function called from debug console. That is currently not supported. Debug console executes code in a spawned process. If that process does not return in reasonable time (10s IIRC) it's getting terminated. That explains the message.

Instead of triggering your function from the console you can run it from a test or mix task. If you need to do it from the console, you can always spawn an unlinked task
