### ISSUE TITLE
Are you planning add support iex -S mix debugging?

### ISSUE THREAD

**Issue by big-town** [elixir-lsp/vscode-elixir-ls#47]
Hello. Are you planning add support iex -S mix debugging?

**Comment by axelson** [comment]
Can you explain more about what you mean by "iex -S mix debugging"?

**Comment by k-qb** [comment]
I can imagine what big-town is asking for, because I might have the same request.
It's pretty simple.
I want to attach an iex session via --remsh, so I can use the iex session to execute code, that runs into a breakpoint and can such be debugged.

I achieved this by adding an "sname" to the elixir invocation in the debugger.sh

In the following file:
.vscode/extensions/elixir-lsp.elixir-ls-0.3.2/elixir-ls-release/debugger.sh
I changed the elixir line to:
elixir --sname debug -e "ElixirLS.Debugger.CLI.main()"

Then i can attach to that process with:
iex -S mix --remsh debug --sname debug-client

Obviously the sname could be something else.
Unfortunately, I'm a newbie about github and pull-requests.

**Comment by big-town** [comment]
Excuse me I didn’t answer for so long.   I mean for the debugging process in interactive mode. For example: I run my application like this: iex --name service@host. Usually I execute set of command :debugger.start, :int.ni Module, :int.break Module, row. Similar algorithm implements the Idea IDE with an extension for elixir.

**Comment by lukaszsamson** [comment]
A PR would be welcome

**Comment by lukaszsamson** [comment]
`ELS_ELIXIR_OPTS` and `ELS_ERL_OPTS` are now supported. You can pass `--sname --cookie mycookie` via `ELS_ELIXIR_OPTS` and connect to it from iex session. I believe this issue is now resolved.
